//! Bevy-like API layer for MassEntity.
//!
//! Provides `MassFragment` trait, query types with compile-time mut/immut
//! enforcement, and registration infrastructure for dynamic mass system dispatch.
//!
//! Query types:
//! - `MassQuery<&T>` / `MassQuery<&mut T>` — primary per-chunk query (user syntax)
//! - `MassQueryAll<&T>` / `MassQueryAll<&mut T>` — global cross-archetype query (user syntax)
//!
//! The proc macro maps these to concrete types:
//! - `MassQueryRef<T>` — read-only per-chunk
//! - `MassQueryMut<T>` — read-write per-chunk
//! - `MassQueryAllRef<T>` — read-only global
//! - `MassQueryAllMut<T>` — read-write global

use std::ffi::c_void;

/// Trait implemented by `#[derive(MassFragment)]` on `#[repr(C)]` structs
/// that match a C++ MassEntity USTRUCT.
pub trait MassFragment: Sized + Copy + 'static {
    /// The C++ USTRUCT type name (e.g. "FGatherersMassAntFragment").
    const CPP_TYPE_NAME: &'static str;
}

/// Compile-time registration entry for a MassFragment, collected via inventory.
pub struct MassFragmentRegistration {
    pub cpp_type_name: &'static str,
    pub rust_type_name: &'static str,
    pub size: usize,
    pub align: usize,
}

inventory::collect!(MassFragmentRegistration);

/// Returns all registered MassFragment types.
pub fn registered_mass_fragments() -> inventory::iter<MassFragmentRegistration> {
    inventory::iter::<MassFragmentRegistration>
}

// ---------------------------------------------------------------------------
// Primary query types (per-chunk)
// ---------------------------------------------------------------------------

/// Read-only view over fragment data in a chunk.
/// Generated by the macro for `MassQuery<&T>`.
pub struct MassQueryRef<'a, T: MassFragment> {
    data: &'a [T],
}

impl<'a, T: MassFragment> MassQueryRef<'a, T> {
    /// # Safety
    /// `ptr` must point to a valid array of `count` elements of type `T`.
    pub unsafe fn from_raw(ptr: *const c_void, count: usize) -> Self {
        let data = unsafe { std::slice::from_raw_parts(ptr as *const T, count) };
        Self { data }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.data.iter()
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn as_slice(&self) -> &[T] {
        self.data
    }
}

/// Read-write view over fragment data in a chunk.
/// Generated by the macro for `MassQuery<&mut T>`.
pub struct MassQueryMut<'a, T: MassFragment> {
    data: &'a mut [T],
}

impl<'a, T: MassFragment> MassQueryMut<'a, T> {
    /// # Safety
    /// `ptr` must point to a valid array of `count` elements of type `T`.
    pub unsafe fn from_raw(ptr: *mut c_void, count: usize) -> Self {
        let data = unsafe { std::slice::from_raw_parts_mut(ptr as *mut T, count) };
        Self { data }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.data.iter()
    }

    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, T> {
        self.data.iter_mut()
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn as_slice(&self) -> &[T] {
        self.data
    }

    pub fn as_mut_slice(&mut self) -> &mut [T] {
        self.data
    }
}

// ---------------------------------------------------------------------------
// Global query types (cross-archetype, all matching entities, zero-copy)
// ---------------------------------------------------------------------------

/// Read-only view over ALL entities matching a fragment type, across all chunks.
/// Zero-copy: points directly into Mass Entity chunk memory.
/// Generated by the macro for `MassQueryAll<&T>`.
pub struct MassQueryAllRef<'a, T: MassFragment> {
    desc: &'a unreal_ffi::MassGlobalFragmentChunks,
    _phantom: std::marker::PhantomData<&'a T>,
}

impl<'a, T: MassFragment> MassQueryAllRef<'a, T> {
    /// Construct from a chunked descriptor (zero-copy path, used by generated code).
    ///
    /// # Safety
    /// `desc` must point to a valid `MassGlobalFragmentChunks` whose chunk data pointers
    /// are valid for `'a` and contain properly laid out `T` values.
    pub unsafe fn from_chunked(desc: *const unreal_ffi::MassGlobalFragmentChunks) -> Self {
        Self {
            desc: unsafe { &*desc },
            _phantom: std::marker::PhantomData,
        }
    }

    /// Construct from a contiguous slice (for tests).
    ///
    /// # Safety
    /// `ptr` must point to a valid array of `count` elements of type `T`.
    pub unsafe fn from_raw_single_chunk(
        ptr: *const c_void,
        count: usize,
        chunk_storage: &'a mut MassGlobalChunkStorage,
    ) -> Self {
        chunk_storage.init_single(ptr as *mut c_void, count, std::mem::size_of::<T>());
        Self {
            desc: &chunk_storage.desc,
            _phantom: std::marker::PhantomData,
        }
    }

    pub fn get(&self, global_index: usize) -> Option<&T> {
        chunked_get(self.desc, global_index)
    }

    pub fn iter(&self) -> MassQueryAllIter<'_, T> {
        MassQueryAllIter::new(self.desc)
    }

    pub fn len(&self) -> usize {
        self.desc.total_count as usize
    }

    pub fn is_empty(&self) -> bool {
        self.desc.total_count == 0
    }
}

/// Read-write view over ALL entities matching a fragment type, across all chunks.
/// Zero-copy: points directly into Mass Entity chunk memory, no write-back needed.
/// Generated by the macro for `MassQueryAll<&mut T>`.
pub struct MassQueryAllMut<'a, T: MassFragment> {
    desc: &'a unreal_ffi::MassGlobalFragmentChunks,
    _phantom: std::marker::PhantomData<&'a mut T>,
}

impl<'a, T: MassFragment> MassQueryAllMut<'a, T> {
    /// Construct from a chunked descriptor (zero-copy path, used by generated code).
    ///
    /// # Safety
    /// `desc` must point to a valid `MassGlobalFragmentChunks` whose chunk data pointers
    /// are valid for `'a` and contain properly laid out `T` values.
    pub unsafe fn from_chunked(desc: *const unreal_ffi::MassGlobalFragmentChunks) -> Self {
        Self {
            desc: unsafe { &*desc },
            _phantom: std::marker::PhantomData,
        }
    }

    /// Construct from a contiguous slice (for tests).
    ///
    /// # Safety
    /// `ptr` must point to a valid mutable array of `count` elements of type `T`.
    pub unsafe fn from_raw_single_chunk(
        ptr: *mut c_void,
        count: usize,
        chunk_storage: &'a mut MassGlobalChunkStorage,
    ) -> Self {
        chunk_storage.init_single(ptr, count, std::mem::size_of::<T>());
        Self {
            desc: &chunk_storage.desc,
            _phantom: std::marker::PhantomData,
        }
    }

    pub fn get(&self, global_index: usize) -> Option<&T> {
        chunked_get(self.desc, global_index)
    }

    pub fn get_mut(&mut self, global_index: usize) -> Option<&mut T> {
        chunked_get_mut(self.desc, global_index)
    }

    pub fn iter(&self) -> MassQueryAllIter<'_, T> {
        MassQueryAllIter::new(self.desc)
    }

    pub fn iter_mut(&mut self) -> MassQueryAllIterMut<'_, T> {
        MassQueryAllIterMut::new(self.desc)
    }

    pub fn len(&self) -> usize {
        self.desc.total_count as usize
    }

    pub fn is_empty(&self) -> bool {
        self.desc.total_count == 0
    }
}

// ---------------------------------------------------------------------------
// Chunked access helpers
// ---------------------------------------------------------------------------

/// Heap storage for a single-chunk descriptor, used in tests.
/// Keeps the `MassGlobalChunkSlice` and `MassGlobalFragmentChunks` alive.
pub struct MassGlobalChunkStorage {
    chunk: unreal_ffi::MassGlobalChunkSlice,
    desc: unreal_ffi::MassGlobalFragmentChunks,
}

impl MassGlobalChunkStorage {
    pub fn new() -> Self {
        Self {
            chunk: unreal_ffi::MassGlobalChunkSlice {
                data: std::ptr::null_mut(),
                count: 0,
                stride: 0,
            },
            desc: unreal_ffi::MassGlobalFragmentChunks {
                chunks: std::ptr::null(),
                num_chunks: 0,
                total_count: 0,
                stride: 0,
            },
        }
    }

    fn init_single(&mut self, ptr: *mut c_void, count: usize, stride: usize) {
        self.chunk = unreal_ffi::MassGlobalChunkSlice {
            data: ptr,
            count: count as i32,
            stride: stride as u32,
        };
        self.desc = unreal_ffi::MassGlobalFragmentChunks {
            chunks: &self.chunk as *const _,
            num_chunks: 1,
            total_count: count as i32,
            stride: stride as u32,
        };
    }
}

fn chunked_get<'a, T: MassFragment>(
    desc: &'a unreal_ffi::MassGlobalFragmentChunks,
    global_index: usize,
) -> Option<&'a T> {
    let mut remaining = global_index;
    for i in 0..desc.num_chunks as usize {
        let chunk = unsafe { &*desc.chunks.add(i) };
        let count = chunk.count as usize;
        if remaining < count {
            return Some(unsafe { &*(chunk.data as *const T).add(remaining) });
        }
        remaining -= count;
    }
    None
}

fn chunked_get_mut<'a, T: MassFragment>(
    desc: &'a unreal_ffi::MassGlobalFragmentChunks,
    global_index: usize,
) -> Option<&'a mut T> {
    let mut remaining = global_index;
    for i in 0..desc.num_chunks as usize {
        let chunk = unsafe { &*desc.chunks.add(i) };
        let count = chunk.count as usize;
        if remaining < count {
            return Some(unsafe { &mut *(chunk.data as *mut T).add(remaining) });
        }
        remaining -= count;
    }
    None
}

/// Read-only iterator across all chunks of a global query.
pub struct MassQueryAllIter<'a, T: MassFragment> {
    desc: &'a unreal_ffi::MassGlobalFragmentChunks,
    chunk_idx: usize,
    offset: usize,
    _phantom: std::marker::PhantomData<&'a T>,
}

impl<'a, T: MassFragment> MassQueryAllIter<'a, T> {
    fn new(desc: &'a unreal_ffi::MassGlobalFragmentChunks) -> Self {
        Self {
            desc,
            chunk_idx: 0,
            offset: 0,
            _phantom: std::marker::PhantomData,
        }
    }
}

impl<'a, T: MassFragment> Iterator for MassQueryAllIter<'a, T> {
    type Item = &'a T;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            if self.chunk_idx >= self.desc.num_chunks as usize {
                return None;
            }
            let chunk = unsafe { &*self.desc.chunks.add(self.chunk_idx) };
            if self.offset < chunk.count as usize {
                let item = unsafe { &*(chunk.data as *const T).add(self.offset) };
                self.offset += 1;
                return Some(item);
            }
            self.chunk_idx += 1;
            self.offset = 0;
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let total = self.desc.total_count as usize;
        (0, Some(total))
    }
}

/// Mutable iterator across all chunks of a global query.
pub struct MassQueryAllIterMut<'a, T: MassFragment> {
    desc: &'a unreal_ffi::MassGlobalFragmentChunks,
    chunk_idx: usize,
    offset: usize,
    _phantom: std::marker::PhantomData<&'a mut T>,
}

impl<'a, T: MassFragment> MassQueryAllIterMut<'a, T> {
    fn new(desc: &'a unreal_ffi::MassGlobalFragmentChunks) -> Self {
        Self {
            desc,
            chunk_idx: 0,
            offset: 0,
            _phantom: std::marker::PhantomData,
        }
    }
}

impl<'a, T: MassFragment> Iterator for MassQueryAllIterMut<'a, T> {
    type Item = &'a mut T;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            if self.chunk_idx >= self.desc.num_chunks as usize {
                return None;
            }
            let chunk = unsafe { &*self.desc.chunks.add(self.chunk_idx) };
            if self.offset < chunk.count as usize {
                let item = unsafe { &mut *(chunk.data as *mut T).add(self.offset) };
                self.offset += 1;
                return Some(item);
            }
            self.chunk_idx += 1;
            self.offset = 0;
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let total = self.desc.total_count as usize;
        (0, Some(total))
    }
}

// ---------------------------------------------------------------------------
// Backward compatibility: keep MassQuery as alias for generated code
// ---------------------------------------------------------------------------

/// Deprecated: use `MassQueryMut` or `MassQueryRef` directly.
/// Kept for backward compatibility with existing generated code.
pub type MassQuery<'a, T> = MassQueryMut<'a, T>;

// ---------------------------------------------------------------------------
// User-facing marker types (used in function signatures, never constructed)
// ---------------------------------------------------------------------------

/// Marker type for global cross-archetype queries in `#[mass_system]` signatures.
/// Users write `MassQueryAll<&T>` or `MassQueryAll<&mut T>`.
/// The proc macro maps these to `MassQueryAllRef<T>` or `MassQueryAllMut<T>`.
pub struct MassQueryAll<T> {
    _phantom: std::marker::PhantomData<T>,
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

/// Registration entry for a dynamically registered mass system, collected via inventory.
pub struct MassSystemRegistration {
    pub name: &'static str,
    pub execute_fn: unsafe extern "C" fn(*const unreal_ffi::MassChunkData),
    pub requirements: &'static [MassSystemRequirement],
}

inventory::collect!(MassSystemRegistration);

/// Describes one fragment requirement for a mass system.
pub struct MassSystemRequirement {
    pub cpp_type_name: &'static str,
    pub size: usize,
    pub align: usize,
    pub access_mode: u8,  // 0 = ReadOnly, 1 = ReadWrite
    pub is_tag: u8,       // 0 = fragment, 1 = tag
    pub query_scope: u8,  // 0 = primary (per-chunk), 1 = global (all)
}

/// Returns all registered mass systems.
pub fn registered_mass_systems() -> inventory::iter<MassSystemRegistration> {
    inventory::iter::<MassSystemRegistration>
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Clone, Copy)]
    #[repr(C)]
    struct TestFragment {
        x: f64,
        y: f64,
    }

    impl MassFragment for TestFragment {
        const CPP_TYPE_NAME: &'static str = "FTestFragment";
    }

    #[test]
    fn mass_query_ref_from_slice() {
        let data = [
            TestFragment { x: 1.0, y: 2.0 },
            TestFragment { x: 3.0, y: 4.0 },
        ];
        let query = unsafe {
            MassQueryRef::<TestFragment>::from_raw(
                data.as_ptr() as *const c_void,
                data.len(),
            )
        };
        assert_eq!(query.len(), 2);
        assert!(!query.is_empty());
        let xs: Vec<f64> = query.iter().map(|f| f.x).collect();
        assert_eq!(xs, vec![1.0, 3.0]);
    }

    #[test]
    fn mass_query_mut_from_slice() {
        let mut data = [
            TestFragment { x: 1.0, y: 2.0 },
            TestFragment { x: 3.0, y: 4.0 },
        ];
        let mut query = unsafe {
            MassQueryMut::<TestFragment>::from_raw(
                data.as_mut_ptr() as *mut c_void,
                data.len(),
            )
        };
        for frag in query.iter_mut() {
            frag.x += 10.0;
        }
        assert_eq!(data[0].x, 11.0);
        assert_eq!(data[1].x, 13.0);
    }

    #[test]
    fn mass_query_all_ref_chunked() {
        let data = [
            TestFragment { x: 5.0, y: 6.0 },
            TestFragment { x: 7.0, y: 8.0 },
        ];
        let mut storage = MassGlobalChunkStorage::new();
        let query = unsafe {
            MassQueryAllRef::<TestFragment>::from_raw_single_chunk(
                data.as_ptr() as *const c_void,
                data.len(),
                &mut storage,
            )
        };
        assert_eq!(query.len(), 2);
        assert!(!query.is_empty());
        assert_eq!(query.get(0).unwrap().x, 5.0);
        assert_eq!(query.get(1).unwrap().x, 7.0);
        assert!(query.get(2).is_none());
        assert_eq!(query.iter().map(|f| f.x).collect::<Vec<_>>(), vec![5.0, 7.0]);
    }

    #[test]
    fn mass_query_all_mut_chunked() {
        let mut data = [
            TestFragment { x: 1.0, y: 2.0 },
            TestFragment { x: 3.0, y: 4.0 },
        ];
        let mut storage = MassGlobalChunkStorage::new();
        let mut query = unsafe {
            MassQueryAllMut::<TestFragment>::from_raw_single_chunk(
                data.as_mut_ptr() as *mut c_void,
                data.len(),
                &mut storage,
            )
        };
        assert_eq!(query.len(), 2);
        query.get_mut(0).unwrap().x = 99.0;
        assert_eq!(data[0].x, 99.0);
        // iter_mut
        for frag in query.iter_mut() {
            frag.y += 10.0;
        }
        assert_eq!(data[0].y, 12.0);
        assert_eq!(data[1].y, 14.0);
    }

    #[test]
    fn mass_query_all_multi_chunk() {
        let mut data1 = [TestFragment { x: 1.0, y: 2.0 }];
        let mut data2 = [
            TestFragment { x: 3.0, y: 4.0 },
            TestFragment { x: 5.0, y: 6.0 },
        ];
        let chunks = [
            unreal_ffi::MassGlobalChunkSlice {
                data: data1.as_mut_ptr() as *mut c_void,
                count: 1,
                stride: std::mem::size_of::<TestFragment>() as u32,
            },
            unreal_ffi::MassGlobalChunkSlice {
                data: data2.as_mut_ptr() as *mut c_void,
                count: 2,
                stride: std::mem::size_of::<TestFragment>() as u32,
            },
        ];
        let desc = unreal_ffi::MassGlobalFragmentChunks {
            chunks: chunks.as_ptr(),
            num_chunks: 2,
            total_count: 3,
            stride: std::mem::size_of::<TestFragment>() as u32,
        };
        let mut query = unsafe { MassQueryAllMut::<TestFragment>::from_chunked(&desc) };
        assert_eq!(query.len(), 3);
        // get across chunk boundary
        assert_eq!(query.get(0).unwrap().x, 1.0);
        assert_eq!(query.get(1).unwrap().x, 3.0);
        assert_eq!(query.get(2).unwrap().x, 5.0);
        assert!(query.get(3).is_none());
        // mutate in second chunk
        query.get_mut(2).unwrap().x = 99.0;
        assert_eq!(data2[1].x, 99.0);
        // iter collects all
        let xs: Vec<f64> = query.iter().map(|f| f.x).collect();
        assert_eq!(xs, vec![1.0, 3.0, 99.0]);
    }

    #[test]
    fn mass_fragment_trait() {
        assert_eq!(TestFragment::CPP_TYPE_NAME, "FTestFragment");
        assert_eq!(std::mem::size_of::<TestFragment>(), 16);
    }

    #[test]
    fn backward_compat_mass_query_alias() {
        // MassQuery is now an alias for MassQueryMut
        let mut data = [TestFragment { x: 1.0, y: 2.0 }];
        let mut query = unsafe {
            MassQuery::<TestFragment>::from_raw(
                data.as_mut_ptr() as *mut c_void,
                data.len(),
            )
        };
        query.iter_mut().for_each(|f| f.x += 1.0);
        assert_eq!(data[0].x, 2.0);
    }
}
