//! Bevy-like API layer for MassEntity.
//!
//! Provides `MassFragment` trait, query types with compile-time mut/immut
//! enforcement, and registration infrastructure for dynamic mass system dispatch.
//!
//! Query types:
//! - `MassQuery<&T>` / `MassQuery<&mut T>` — primary per-chunk query (user syntax)
//! - `MassQueryAll<&T>` / `MassQueryAll<&mut T>` — global cross-archetype query (user syntax)
//!
//! The proc macro maps these to concrete types:
//! - `MassQueryRef<T>` — read-only per-chunk
//! - `MassQueryMut<T>` — read-write per-chunk
//! - `MassQueryAllRef<T>` — read-only global
//! - `MassQueryAllMut<T>` — read-write global

use std::ffi::c_void;

/// Trait implemented by `#[derive(MassFragment)]` on `#[repr(C)]` structs
/// that match a C++ MassEntity USTRUCT.
pub trait MassFragment: Sized + Copy + 'static {
    /// The C++ USTRUCT type name (e.g. "FGatherersMassAntFragment").
    const CPP_TYPE_NAME: &'static str;
}

/// Compile-time registration entry for a MassFragment, collected via inventory.
pub struct MassFragmentRegistration {
    pub cpp_type_name: &'static str,
    pub rust_type_name: &'static str,
    pub size: usize,
    pub align: usize,
}

inventory::collect!(MassFragmentRegistration);

/// Returns all registered MassFragment types.
pub fn registered_mass_fragments() -> inventory::iter<MassFragmentRegistration> {
    inventory::iter::<MassFragmentRegistration>
}

// ---------------------------------------------------------------------------
// Primary query types (per-chunk)
// ---------------------------------------------------------------------------

/// Read-only view over fragment data in a chunk.
/// Generated by the macro for `MassQuery<&T>`.
pub struct MassQueryRef<'a, T: MassFragment> {
    data: &'a [T],
}

impl<'a, T: MassFragment> MassQueryRef<'a, T> {
    /// # Safety
    /// `ptr` must point to a valid array of `count` elements of type `T`.
    pub unsafe fn from_raw(ptr: *const c_void, count: usize) -> Self {
        let data = unsafe { std::slice::from_raw_parts(ptr as *const T, count) };
        Self { data }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.data.iter()
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn as_slice(&self) -> &[T] {
        self.data
    }
}

/// Read-write view over fragment data in a chunk.
/// Generated by the macro for `MassQuery<&mut T>`.
pub struct MassQueryMut<'a, T: MassFragment> {
    data: &'a mut [T],
}

impl<'a, T: MassFragment> MassQueryMut<'a, T> {
    /// # Safety
    /// `ptr` must point to a valid array of `count` elements of type `T`.
    pub unsafe fn from_raw(ptr: *mut c_void, count: usize) -> Self {
        let data = unsafe { std::slice::from_raw_parts_mut(ptr as *mut T, count) };
        Self { data }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.data.iter()
    }

    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, T> {
        self.data.iter_mut()
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn as_slice(&self) -> &[T] {
        self.data
    }

    pub fn as_mut_slice(&mut self) -> &mut [T] {
        self.data
    }
}

// ---------------------------------------------------------------------------
// Global query types (cross-archetype, all matching entities)
// ---------------------------------------------------------------------------

/// Read-only view over ALL entities matching a fragment type, across all chunks.
/// Generated by the macro for `MassQueryAll<&T>`.
pub struct MassQueryAllRef<'a, T: MassFragment> {
    data: &'a [T],
    entity_handles: &'a [[i32; 2]],
}

impl<'a, T: MassFragment> MassQueryAllRef<'a, T> {
    /// # Safety
    /// `ptr` must point to a valid array of `count` elements.
    /// `handles_ptr` must point to `count` pairs of `[i32; 2]`.
    pub unsafe fn from_raw(ptr: *const c_void, handles_ptr: *const i32, count: usize) -> Self {
        let data = unsafe { std::slice::from_raw_parts(ptr as *const T, count) };
        let entity_handles =
            unsafe { std::slice::from_raw_parts(handles_ptr as *const [i32; 2], count) };
        Self {
            data,
            entity_handles,
        }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.data.iter()
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn as_slice(&self) -> &[T] {
        self.data
    }

    /// Returns the entity handle [index, serial_number] for the entity at `idx`.
    pub fn entity_handle(&self, idx: usize) -> [i32; 2] {
        self.entity_handles[idx]
    }

    pub fn entity_handles(&self) -> &[[i32; 2]] {
        self.entity_handles
    }
}

/// Read-write view over ALL entities matching a fragment type, across all chunks.
/// Generated by the macro for `MassQueryAll<&mut T>`.
pub struct MassQueryAllMut<'a, T: MassFragment> {
    data: &'a mut [T],
    entity_handles: &'a [[i32; 2]],
}

impl<'a, T: MassFragment> MassQueryAllMut<'a, T> {
    /// # Safety
    /// `ptr` must point to a valid array of `count` elements.
    /// `handles_ptr` must point to `count` pairs of `[i32; 2]`.
    pub unsafe fn from_raw(ptr: *mut c_void, handles_ptr: *const i32, count: usize) -> Self {
        let data = unsafe { std::slice::from_raw_parts_mut(ptr as *mut T, count) };
        let entity_handles =
            unsafe { std::slice::from_raw_parts(handles_ptr as *const [i32; 2], count) };
        Self {
            data,
            entity_handles,
        }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.data.iter()
    }

    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, T> {
        self.data.iter_mut()
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn as_slice(&self) -> &[T] {
        self.data
    }

    pub fn as_mut_slice(&mut self) -> &mut [T] {
        self.data
    }

    /// Returns the entity handle [index, serial_number] for the entity at `idx`.
    pub fn entity_handle(&self, idx: usize) -> [i32; 2] {
        self.entity_handles[idx]
    }

    pub fn entity_handles(&self) -> &[[i32; 2]] {
        self.entity_handles
    }

    /// Returns mutable data slice and entity handles simultaneously,
    /// avoiding borrow-checker issues when both are needed at once.
    pub fn split_mut(&mut self) -> (&mut [T], &[[i32; 2]]) {
        (self.data, self.entity_handles)
    }
}

// ---------------------------------------------------------------------------
// Backward compatibility: keep MassQuery as alias for generated code
// ---------------------------------------------------------------------------

/// Deprecated: use `MassQueryMut` or `MassQueryRef` directly.
/// Kept for backward compatibility with existing generated code.
pub type MassQuery<'a, T> = MassQueryMut<'a, T>;

// ---------------------------------------------------------------------------
// User-facing marker types (used in function signatures, never constructed)
// ---------------------------------------------------------------------------

/// Marker type for global cross-archetype queries in `#[mass_system]` signatures.
/// Users write `MassQueryAll<&T>` or `MassQueryAll<&mut T>`.
/// The proc macro maps these to `MassQueryAllRef<T>` or `MassQueryAllMut<T>`.
pub struct MassQueryAll<T> {
    _phantom: std::marker::PhantomData<T>,
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

/// Registration entry for a dynamically registered mass system, collected via inventory.
pub struct MassSystemRegistration {
    pub name: &'static str,
    pub execute_fn: unsafe extern "C" fn(*const unreal_ffi::MassChunkData),
    pub requirements: &'static [MassSystemRequirement],
}

inventory::collect!(MassSystemRegistration);

/// Describes one fragment requirement for a mass system.
pub struct MassSystemRequirement {
    pub cpp_type_name: &'static str,
    pub size: usize,
    pub align: usize,
    pub access_mode: u8,  // 0 = ReadOnly, 1 = ReadWrite
    pub is_tag: u8,       // 0 = fragment, 1 = tag
    pub query_scope: u8,  // 0 = primary (per-chunk), 1 = global (all)
}

/// Returns all registered mass systems.
pub fn registered_mass_systems() -> inventory::iter<MassSystemRegistration> {
    inventory::iter::<MassSystemRegistration>
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Clone, Copy)]
    #[repr(C)]
    struct TestFragment {
        x: f64,
        y: f64,
    }

    impl MassFragment for TestFragment {
        const CPP_TYPE_NAME: &'static str = "FTestFragment";
    }

    #[test]
    fn mass_query_ref_from_slice() {
        let data = [
            TestFragment { x: 1.0, y: 2.0 },
            TestFragment { x: 3.0, y: 4.0 },
        ];
        let query = unsafe {
            MassQueryRef::<TestFragment>::from_raw(
                data.as_ptr() as *const c_void,
                data.len(),
            )
        };
        assert_eq!(query.len(), 2);
        assert!(!query.is_empty());
        let xs: Vec<f64> = query.iter().map(|f| f.x).collect();
        assert_eq!(xs, vec![1.0, 3.0]);
    }

    #[test]
    fn mass_query_mut_from_slice() {
        let mut data = [
            TestFragment { x: 1.0, y: 2.0 },
            TestFragment { x: 3.0, y: 4.0 },
        ];
        let mut query = unsafe {
            MassQueryMut::<TestFragment>::from_raw(
                data.as_mut_ptr() as *mut c_void,
                data.len(),
            )
        };
        for frag in query.iter_mut() {
            frag.x += 10.0;
        }
        assert_eq!(data[0].x, 11.0);
        assert_eq!(data[1].x, 13.0);
    }

    #[test]
    fn mass_query_all_ref_with_handles() {
        let data = [
            TestFragment { x: 5.0, y: 6.0 },
            TestFragment { x: 7.0, y: 8.0 },
        ];
        let handles: [[i32; 2]; 2] = [[1, 100], [2, 200]];
        let query = unsafe {
            MassQueryAllRef::<TestFragment>::from_raw(
                data.as_ptr() as *const c_void,
                handles.as_ptr() as *const i32,
                data.len(),
            )
        };
        assert_eq!(query.len(), 2);
        assert_eq!(query.entity_handle(0), [1, 100]);
        assert_eq!(query.entity_handle(1), [2, 200]);
        assert_eq!(query.iter().map(|f| f.x).collect::<Vec<_>>(), vec![5.0, 7.0]);
    }

    #[test]
    fn mass_query_all_mut_with_handles() {
        let mut data = [
            TestFragment { x: 1.0, y: 2.0 },
        ];
        let handles: [[i32; 2]; 1] = [[42, 999]];
        let mut query = unsafe {
            MassQueryAllMut::<TestFragment>::from_raw(
                data.as_mut_ptr() as *mut c_void,
                handles.as_ptr() as *const i32,
                data.len(),
            )
        };
        query.as_mut_slice()[0].x = 99.0;
        assert_eq!(data[0].x, 99.0);
        assert_eq!(query.entity_handle(0), [42, 999]);
    }

    #[test]
    fn mass_fragment_trait() {
        assert_eq!(TestFragment::CPP_TYPE_NAME, "FTestFragment");
        assert_eq!(std::mem::size_of::<TestFragment>(), 16);
    }

    #[test]
    fn backward_compat_mass_query_alias() {
        // MassQuery is now an alias for MassQueryMut
        let mut data = [TestFragment { x: 1.0, y: 2.0 }];
        let mut query = unsafe {
            MassQuery::<TestFragment>::from_raw(
                data.as_mut_ptr() as *mut c_void,
                data.len(),
            )
        };
        query.iter_mut().for_each(|f| f.x += 1.0);
        assert_eq!(data[0].x, 2.0);
    }
}
