#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(non_camel_case_types)]
pub use crate::bindings::prelude::*;
#[repr(C, align(8))]
pub struct FChaosDestructionEvent {
    pub position: FVector,
    pub normal: FVector,
    pub velocity: FVector,
    pub angular_velocity: FVector,
    pub extent_min: f32,
    pub extent_max: f32,
    pub particle_id: i32,
    pub time: f32,
    pub ty: i32,
}
pub struct UNiagaraDataInterfaceChaosDestruction {
    pub chaos_solver_actor_set: TSet<UPtr<AChaosSolverActor>>,
    pub data_source_type: EDataSourceTypeEnum,
    pub data_process_frequency: i32,
    pub max_number_of_data_entries_to_spawn: i32,
    pub do_spawn: bool,
    pub spawn_multiplier_min_max: FVector2D,
    pub spawn_chance: f32,
    pub impulse_to_spawn_min_max: FVector2D,
    pub speed_to_spawn_min_max: FVector2D,
    pub mass_to_spawn_min_max: FVector2D,
    pub extent_min_to_spawn_min_max: FVector2D,
    pub extent_max_to_spawn_min_max: FVector2D,
    pub volume_to_spawn_min_max: FVector2D,
    pub solver_time_to_spawn_min_max: FVector2D,
    pub surface_type_to_spawn: i32,
    pub location_filtering_mode: ELocationFilteringModeEnum,
    pub location_x_to_spawn: ELocationXToSpawnEnum,
    pub location_x_to_spawn_min_max: FVector2D,
    pub location_y_to_spawn: ELocationYToSpawnEnum,
    pub location_y_to_spawn_min_max: FVector2D,
    pub location_z_to_spawn: ELocationZToSpawnEnum,
    pub location_z_to_spawn_min_max: FVector2D,
    pub trail_min_speed_to_spawn: f32,
    pub data_sorting_type: EDataSortTypeEnum,
    pub b_get_external_collision_data: bool,
    pub do_spatial_hash: bool,
    pub spatial_hash_volume_min: FVector,
    pub spatial_hash_volume_max: FVector,
    pub spatial_hash_volume_cell_size: FVector,
    pub max_data_per_cell: i32,
    pub b_apply_materials_filter: bool,
    pub chaos_breaking_material_set: TSet<UPtr<UPhysicalMaterial>>,
    pub b_get_external_breaking_data: bool,
    pub b_get_external_trailing_data: bool,
    pub random_position_magnitude_min_max: FVector2D,
    pub inherited_velocity_multiplier: f32,
    pub random_velocity_generation_type: ERandomVelocityGenerationTypeEnum,
    pub random_velocity_magnitude_min_max: FVector2D,
    pub spread_angle_max: f32,
    pub velocity_offset_min: FVector,
    pub velocity_offset_max: FVector,
    pub final_velocity_magnitude_min_max: FVector2D,
    pub max_latency: f32,
    pub debug_type: EDebugTypeEnum,
    pub last_spawned_point_id: i32,
    pub last_spawn_time: f32,
    pub solver_time: f32,
    pub time_stamp_of_last_processed_data: f32,
}
pub struct UNiagaraDataInterfaceGeometryCollection {
    pub source_mode: ENDIGeometryCollection_SourceMode,
    pub preview_collection: TSoftObjectPtr<UGeometryCollection>,
    pub default_geometry_collection: UPtr<UGeometryCollection>,
    pub geometry_collection_actor: TSoftObjectPtr<AGeometryCollectionActor>,
    pub source_component: UPtr<UGeometryCollectionComponent>,
    pub geometry_collection_user_parameter: FNiagaraUserParameterBinding,
    pub b_include_intermediate_bones: bool,
}
pub struct UNiagaraDataInterfacePhysicsField {}
