#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(non_camel_case_types)]
pub use crate::bindings::prelude::*;
pub struct UAssetDefinition_ActorFolder {}
pub struct UAssetDefinition_ActorFoliageSettings {}
pub struct UAssetDefinition_AnimationAsset {}
pub struct UAssetDefinition_BlendSpace {}
pub struct UAssetDefinition_AimOffset {}
pub struct UAssetDefinition_BlendSpace1D {}
pub struct UAssetDefinition_AimOffset1D {}
pub struct UAssetDefinition_ClassTypeBase {}
pub struct UAssetDefinition_BlueprintGeneratedClass {}
pub struct UAssetDefinition_AnimBlueprintGeneratedClass {}
pub struct UAssetDefinition_AnimComposite {}
pub struct UAssetDefinition_AnimStreamable {}
pub struct UAssetDefinition_Texture {}
pub struct UAssetDefinition_TextureRenderTarget {}
pub struct UAssetDefinition_TextureRenderTarget2D {}
pub struct UAssetDefinition_CanvasRenderTarget2D {}
pub struct UAssetDefinition_CurveTable {}
pub struct UAssetDefinition_CompositeCurveTable {}
pub struct UAssetDefinition_DataTable {}
pub struct UAssetDefinition_CompositeDataTable {}
pub struct UAssetDefinition_Curve {}
pub struct UAssetDefinition_CurveFloat {}
pub struct UAssetDefinition_CurveLinearColor {}
pub struct UAssetDefinition_CurveLinearColorAtlas {}
pub struct UAssetDefinition_CurveVector {}
pub struct UAssetDefinition_DataLayer {}
pub struct UAssetDefinition_DataLayerInstance {}
pub struct UAssetDefinition_ExternalDataLayer {}
pub struct UAssetDefinition_FbxSceneImportData {}
pub struct UAssetDefinition_ForceFeedbackAttenuation {}
pub struct UAssetDefinition_HapticFeedbackEffectBuffer {}
pub struct UAssetDefinition_HapticFeedbackEffectCurve {}
pub struct UAssetDefinition_HapticFeedbackEffectSoundWave {}
pub struct UAssetDefinition_HLODLayer {}
pub struct UAssetDefinition_HLODProxy {}
pub struct UAssetDefinition_InstancedFoliageSettings {}
pub struct UAssetDefinition_LandscapeGrassType {}
pub struct UAssetDefinition_LandscapeLayer {}
pub struct UAssetDefinition_LightWeightInstance {}
pub struct UAssetDefinition_MaterialParameterCollection {}
pub struct UAssetDefinition_NeuralProfile {}
pub struct UAssetDefinition_NodeMappingContainer {}
pub struct UAssetDefinition_ObjectLibrary {}
pub struct UAssetDefinition_PhysicalMaterial {}
pub struct UAssetDefinition_ProceduralFoliageSpawner {}
pub struct UAssetDefinition_SlateBrush {}
pub struct UAssetDefinition_SpecularProfile {}
pub struct UAssetDefinition_SubsurfaceProfile {}
pub struct UAssetDefinition_SubUVAnimation {}
pub struct UAssetDefinition_Texture2DArray {}
pub struct UAssetDefinition_TextureCubeArray {}
pub struct UAssetDefinition_TextureLightProfile {}
pub struct UAssetDefinition_TextureRenderTarget2DArray {}
pub struct UAssetDefinition_TextureRenderTargetCube {}
pub struct UAssetDefinition_TextureRenderTargetVolume {}
pub struct UAssetDefinition_TouchInterface {}
pub struct UAssetDefinition_TransformProviderData {}
pub struct UAssetDefinition_VectorField {}
pub struct UAssetDefinition_VectorFieldAnimated {}
pub struct UAssetDefinition_VectorFieldStatic {}
pub struct UAssetDefinition_VolumeTexture {}
pub struct UAssetDefinition_AnimBank {}
pub struct UAssetDefinition_AnimBankData {}
pub struct UAssetDefinition_Blueprint {}
pub struct UAssetDefinition_AnimBlueprint {}
pub struct UAssetDefinition_AnimMontage {}
pub struct UAssetDefinition_AnimSequence {}
pub struct UAssetDefinition_PoseAsset {}
pub struct UAssetDefinition_SkeletalMesh {}
pub struct UAssetDefinition_Skeleton {}
pub struct UAssetDefinition_Actor {}
pub struct UAssetDefinition_DataAsset {}
pub struct UAssetDefinition_EditorUtilityBlueprint {}
pub struct UAssetDefinition_EditorUtilityWidgetBlueprint {}
pub struct UAssetDefinition_Font {}
pub struct UAssetDefinition_FontFace {}
pub struct UAssetDefinition_ForceFeedbackEffect {}
pub struct UAssetDefinition_PhysicsAsset {}
pub struct UAssetDefinition_Redirector {}
pub struct UAssetDefinition_SlateWidgetStyle {}
pub struct UAssetDefinition_SparseVolumeTexture {}
pub struct UAssetDefinition_StaticSparseVolumeTexture {}
pub struct UAssetDefinition_AnimatedSparseVolumeTexture {}
pub struct UAssetDefinition_StaticMesh {}
pub struct UAssetDefinition_Texture2D {}
pub struct UAssetDefinition_TextureCube {}
pub struct UAssetDefinition_UserDefinedEnum {}
pub struct UAssetDefinition_UserDefinedStruct {}
pub struct UAssetDefinition_World {}
pub struct UAssetDefinition_MaterialInterface {}
pub struct UAssetDefinition_Material {}
pub struct UAssetDefinition_MaterialFunction {}
pub struct UAssetDefinition_MaterialFunctionMaterialLayer {}
pub struct UAssetDefinition_MaterialFunctionLayerBlend {}
pub struct UAssetDefinition_MaterialFunctionInstance {}
pub struct UAssetDefinition_MaterialFunctionLayerInstance {}
pub struct UAssetDefinition_MaterialFunctionLayerBlendInstance {}
pub struct UAssetDefinition_MaterialInstanceConstant {}
pub struct UAssetDefinition_MaterialInstanceDynamic {}
pub struct UAssetDefinition_Class {}
pub struct UAssetDefinition_MirrorDataTable {}
