#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(non_camel_case_types)]
pub use crate::bindings::prelude::*;
#[repr(C, align(8))]
pub struct FPinStructEditWrapper {}
pub struct UGraphEditorSettings {
    pub data_pin_style: EBlueprintPinStyleType,
    pub panning_mouse_button: EGraphPanningMouseButton,
    pub b_use_high_precision_mouse_movement: bool,
    pub b_use_interpolation_with_manual_panning: bool,
    pub padding_above_pin: f32,
    pub padding_below_pin: f32,
    pub padding_right_of_input: f32,
    pub padding_left_of_output: f32,
    pub padding_towards_node_edge: f32,
    pub b_treat_splines_like_pins: bool,
    pub spline_hover_tolerance: f32,
    pub spline_close_tolerance: f32,
    pub forward_spline_horizontal_delta_range: f32,
    pub forward_spline_vertical_delta_range: f32,
    pub forward_spline_tangent_from_horizontal_delta: FDeprecateSlateVector2D,
    pub forward_spline_tangent_from_vertical_delta: FDeprecateSlateVector2D,
    pub backward_spline_horizontal_delta_range: f32,
    pub backward_spline_vertical_delta_range: f32,
    pub backward_spline_tangent_from_horizontal_delta: FDeprecateSlateVector2D,
    pub backward_spline_tangent_from_vertical_delta: FDeprecateSlateVector2D,
    pub default_pin_type_color: FLinearColor,
    pub execution_pin_type_color: FLinearColor,
    pub boolean_pin_type_color: FLinearColor,
    pub byte_pin_type_color: FLinearColor,
    pub class_pin_type_color: FLinearColor,
    pub int_pin_type_color: FLinearColor,
    pub int64_pin_type_color: FLinearColor,
    pub float_pin_type_color: FLinearColor,
    pub double_pin_type_color: FLinearColor,
    pub real_pin_type_color: FLinearColor,
    pub name_pin_type_color: FLinearColor,
    pub soft_object_pin_type_color: FLinearColor,
    pub soft_class_pin_type_color: FLinearColor,
    pub delegate_pin_type_color: FLinearColor,
    pub object_pin_type_color: FLinearColor,
    pub interface_pin_type_color: FLinearColor,
    pub string_pin_type_color: FLinearColor,
    pub text_pin_type_color: FLinearColor,
    pub struct_pin_type_color: FLinearColor,
    pub wildcard_pin_type_color: FLinearColor,
    pub vector_pin_type_color: FLinearColor,
    pub rotator_pin_type_color: FLinearColor,
    pub transform_pin_type_color: FLinearColor,
    pub index_pin_type_color: FLinearColor,
    pub event_node_title_color: FLinearColor,
    pub function_call_node_title_color: FLinearColor,
    pub pure_function_call_node_title_color: FLinearColor,
    pub parent_function_call_node_title_color: FLinearColor,
    pub function_terminator_node_title_color: FLinearColor,
    pub exec_branch_node_title_color: FLinearColor,
    pub exec_sequence_node_title_color: FLinearColor,
    pub result_node_title_color: FLinearColor,
    pub default_comment_node_title_color: FLinearColor,
    pub preview_node_title_color: FLinearColor,
    pub slice_line_color: FLinearColor,
    pub slice_line_dash_length: f32,
    pub slice_line_thickness: f32,
    pub default_data_wire_thickness: f32,
    pub default_execution_wire_thickness: f32,
    pub trace_attack_color: FLinearColor,
    pub trace_attack_wire_thickness: f32,
    pub trace_attack_hold_period: f32,
    pub trace_decay_period: f32,
    pub trace_decay_exponent: f32,
    pub trace_sustain_color: FLinearColor,
    pub trace_sustain_wire_thickness: f32,
    pub trace_sustain_hold_period: f32,
    pub trace_release_color: FLinearColor,
    pub trace_release_wire_thickness: f32,
    pub trace_release_period: f32,
    pub trace_release_exponent: f32,
    pub trace_position_bonus_period: f32,
    pub trace_position_exponent: f32,
    pub padding_auto_collate_increment: f32,
    pub b_open_create_menu_on_blank_graph_areas: bool,
    pub default_comment_node_move_mode: ECommentBoxMode,
    pub b_show_comment_bubble_when_zoomed_out: bool,
}
