use std::env;
use std::fs;
use std::io::Write;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_path = "../RustPlugin/Source/RustPlugin/Bindings.h";

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        // TODO: This is stupid and easy to forgot to add things here. Can we auto detect those?
        .include_item("UnrealBindings")
        .include_item("RustBindings")
        .include_item("CreateRustBindings")
        .include_item("EntryUnrealBindingsFn")
        .include_item("EntryBeginPlayFn")
        .include_item("EntryTickFn")
        .include_item("TryLoadFn")
        .include_item("AActorOpague")
        .include_item("PluginBindings")
        .include_item("FScriptArrayStorage")
        .include_item("FScriptArrayFns")
        .include_item("MassSpatialQueryConfigDesc")
        .include_item("GetSpatialQueryConfigCountFn")
        .include_item("GetSpatialQueryConfigDescFn")
        .include_item("MassSimDefaultsDesc")
        .include_item("GetSimDefaultsFn")
        .include_item("FoodDropEvent")
        .include_item("GetFoodDropEventsFn")
        .include_item("GetFoodPickupEventsFn")
        .include_item("DecisionCounters")
        .include_item("GetDecisionCountersFn")
        .include_item("ResetDecisionCountersFn")
        .with_pragma_once(true)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(output_path);

    // --- Post-process Bindings.h ---

    // 1. Replace cbindgen's Option<T> forward declaration with a full definition
    //    that matches Rust's niche-optimized Option<fn pointer> layout.
    //    Rust represents Option<fn pointer> as just the pointer (null = None),
    //    so Option<T> must NOT include a separate bool field.
    let content = fs::read_to_string(output_path).expect("Failed to read Bindings.h");
    let content = content.replace(
        "template<typename T = void>\nstruct Option;",
        r#"// clang-format off
// NOLINTBEGIN
/// FFI-safe Option type matching Rust's niche-optimized Option<fn pointer> layout.
/// Rust represents Option<fn pointer> as just the pointer (null = None), so this
/// must NOT include a separate bool field. sizeof(Option<T>) must equal sizeof(T).
/// WARNING: Do not add a `bool is_some` field — it breaks the FFI layout.
template<typename T = void>
struct Option {
  T value;
  Option() : value{} {}
  Option(T v) : value(v) {}
  Option& operator=(T v) { value = v; return *this; }
  bool IsSome() const { return value != nullptr; }
  bool IsNone() const { return value == nullptr; }
  T Unwrap() const { return value; }
};
// NOLINTEND
// clang-format on"#,
    );
    fs::write(output_path, &content).expect("Failed to write Bindings.h with Option<T>");

    // 2. Append static_assert block for FFI layout verification.
    //    These values must match the Rust #[test] assertions in lib.rs.
    //    If a Rust struct changes size, the Rust test catches it on the Rust side,
    //    and the static_assert catches the mismatch on the C++ side.
    let mut file = fs::OpenOptions::new()
        .append(true)
        .open(output_path)
        .expect("Failed to reopen Bindings.h for static_asserts");

    writeln!(file, r#"
// =========================================================================
// FFI Layout Verification (auto-generated by unreal-ffi/build.rs)
// These static_asserts catch Rust/C++ struct layout mismatches at compile time.
// Values must match the layout tests in unreal-ffi/src/lib.rs.
// =========================================================================

// --- Option<fn ptr> niche optimization: must be pointer-sized (8 bytes) ---
static_assert(sizeof(Option<SpawnEntitiesFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");
static_assert(sizeof(Option<MassSpatialQueryFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");
static_assert(sizeof(Option<GetVisualizerGroupCountFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");
static_assert(sizeof(Option<GetVisualizerGroupDescFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");
static_assert(sizeof(Option<MassInitSimulationFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");
static_assert(sizeof(Option<GetSpatialQueryConfigCountFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");
static_assert(sizeof(Option<GetSpatialQueryConfigDescFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");
static_assert(sizeof(Option<GetSimDefaultsFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");

// --- Fundamental types ---
static_assert(sizeof(Utf8Str) == 16, "Utf8Str: ptr(8) + usize(8)");
static_assert(alignof(Utf8Str) == 8, "Utf8Str alignment");
static_assert(sizeof(RustAlloc) == 24, "RustAlloc: ptr(8) + usize(8) + usize(8)");
static_assert(alignof(RustAlloc) == 8, "RustAlloc alignment");
static_assert(sizeof(StrRustAlloc) == 24, "StrRustAlloc wraps RustAlloc");

// --- Function table structs ---
static_assert(sizeof(CoreFns) == 72, "CoreFns: 9 fn ptrs");
static_assert(sizeof(FStringFns) == 24, "FStringFns: 3 fn ptrs");
static_assert(sizeof(FScriptArrayFns) == 104, "FScriptArrayFns: 13 fn ptrs");

// --- Binding structs ---
static_assert(sizeof(UnrealBindings) == 216,
    "UnrealBindings: LogFn(8) + CoreFns(72) + FStringFns(24) + FScriptArrayFns(104) + Option<SpawnEntitiesFn>(8)");
static_assert(sizeof(RustBindings) == 160, "RustBindings: 7 fn ptrs + 13 Option<fn ptr> = 20 pointers");
static_assert(sizeof(PluginBindings) == 32, "PluginBindings: 4 fn ptrs");

// --- Mass Entity types ---
static_assert(sizeof(MassEntityHandle) == 8, "MassEntityHandle: i32 + i32");
static_assert(alignof(MassEntityHandle) == 4, "MassEntityHandle alignment");

// --- Spawn types ---
static_assert(sizeof(SpawnFragmentData) == 32, "SpawnFragmentData");
static_assert(alignof(SpawnFragmentData) == 8, "SpawnFragmentData alignment");
static_assert(sizeof(SpawnTagData) == 16, "SpawnTagData: Utf8Str(16)");
static_assert(alignof(SpawnTagData) == 8, "SpawnTagData alignment");
static_assert(sizeof(SpawnEntityRequest) == 40, "SpawnEntityRequest");
static_assert(alignof(SpawnEntityRequest) == 8, "SpawnEntityRequest alignment");
static_assert(offsetof(SpawnEntityRequest, fragments) == 8, "SpawnEntityRequest.fragments offset");

// --- Mass system descriptors ---
static_assert(sizeof(MassFragmentRequirement) == 32, "MassFragmentRequirement");
static_assert(alignof(MassFragmentRequirement) == 8, "MassFragmentRequirement alignment");
static_assert(offsetof(MassFragmentRequirement, access_mode) == 24, "MassFragmentRequirement.access_mode offset");

static_assert(sizeof(MassSystemDescriptor) == 40, "MassSystemDescriptor");
static_assert(alignof(MassSystemDescriptor) == 8, "MassSystemDescriptor alignment");
static_assert(offsetof(MassSystemDescriptor, requirements) == 24, "MassSystemDescriptor.requirements offset");
static_assert(offsetof(MassSystemDescriptor, execute_fn) == 32, "MassSystemDescriptor.execute_fn offset");

// --- Chunk / slice types ---
static_assert(sizeof(MassFragmentSlice) == 16, "MassFragmentSlice");
static_assert(alignof(MassFragmentSlice) == 8, "MassFragmentSlice alignment");

static_assert(sizeof(MassGlobalChunkSlice) == 16, "MassGlobalChunkSlice");
static_assert(alignof(MassGlobalChunkSlice) == 8, "MassGlobalChunkSlice alignment");

static_assert(sizeof(MassGlobalFragmentChunks) == 24, "MassGlobalFragmentChunks");
static_assert(alignof(MassGlobalFragmentChunks) == 8, "MassGlobalFragmentChunks alignment");

static_assert(sizeof(MassChunkData) == 56, "MassChunkData");
static_assert(alignof(MassChunkData) == 8, "MassChunkData alignment");
static_assert(offsetof(MassChunkData, fragments) == 16, "MassChunkData.fragments offset");
static_assert(offsetof(MassChunkData, global_chunked_fragments) == 48, "MassChunkData.global_chunked_fragments offset");

static_assert(sizeof(MassSystemChunkBatch) == 16, "MassSystemChunkBatch");
static_assert(alignof(MassSystemChunkBatch) == 8, "MassSystemChunkBatch alignment");

// --- Spatial query ---
static_assert(sizeof(MassSpatialQueryResult) == 40, "MassSpatialQueryResult");
static_assert(alignof(MassSpatialQueryResult) == 8, "MassSpatialQueryResult alignment");
static_assert(offsetof(MassSpatialQueryResult, encounter_position) == 8, "MassSpatialQueryResult.encounter_position offset");
static_assert(offsetof(MassSpatialQueryResult, has_encounter) == 32, "MassSpatialQueryResult.has_encounter offset");

// --- Spatial query slot ---
static_assert(sizeof(MassSpatialQuerySlot) == 32, "MassSpatialQuerySlot");
static_assert(alignof(MassSpatialQuerySlot) == 8, "MassSpatialQuerySlot alignment");
static_assert(offsetof(MassSpatialQuerySlot, name) == 0, "MassSpatialQuerySlot.name offset");
static_assert(offsetof(MassSpatialQuerySlot, query_fn) == 16, "MassSpatialQuerySlot.query_fn offset");
static_assert(offsetof(MassSpatialQuerySlot, radius) == 24, "MassSpatialQuerySlot.radius offset");

// --- Frame dispatch ---
static_assert(sizeof(MassFrameDispatchData) == 32, "MassFrameDispatchData");
static_assert(alignof(MassFrameDispatchData) == 8, "MassFrameDispatchData alignment");
static_assert(offsetof(MassFrameDispatchData, num_spatial_queries) == 16, "MassFrameDispatchData.num_spatial_queries offset");
static_assert(offsetof(MassFrameDispatchData, spatial_queries) == 24, "MassFrameDispatchData.spatial_queries offset");

// --- Visualizer ---
static_assert(sizeof(MassVisualizerGroupDesc) == 40, "MassVisualizerGroupDesc");
static_assert(alignof(MassVisualizerGroupDesc) == 8, "MassVisualizerGroupDesc alignment");

// --- Simulation init ---
static_assert(sizeof(MassEntityGroupDesc) == 24, "MassEntityGroupDesc");
static_assert(alignof(MassEntityGroupDesc) == 8, "MassEntityGroupDesc alignment");

static_assert(sizeof(MassInitSimulationParams) == 72, "MassInitSimulationParams");
static_assert(alignof(MassInitSimulationParams) == 8, "MassInitSimulationParams alignment");

static_assert(sizeof(MassEntityGroupResult) == 32, "MassEntityGroupResult");
static_assert(alignof(MassEntityGroupResult) == 8, "MassEntityGroupResult alignment");

static_assert(sizeof(MassInitSimulationResult) == 16, "MassInitSimulationResult");
static_assert(alignof(MassInitSimulationResult) == 8, "MassInitSimulationResult alignment");

// --- Spatial query config ---
static_assert(sizeof(MassSpatialQueryConfigDesc) == 64, "MassSpatialQueryConfigDesc");
static_assert(alignof(MassSpatialQueryConfigDesc) == 8, "MassSpatialQueryConfigDesc alignment");
static_assert(offsetof(MassSpatialQueryConfigDesc, query_name) == 0, "MassSpatialQueryConfigDesc.query_name offset");
static_assert(offsetof(MassSpatialQueryConfigDesc, query_group) == 16, "MassSpatialQueryConfigDesc.query_group offset");
static_assert(offsetof(MassSpatialQueryConfigDesc, radius) == 32, "MassSpatialQueryConfigDesc.radius offset");
static_assert(offsetof(MassSpatialQueryConfigDesc, filter_fragment_type) == 40, "MassSpatialQueryConfigDesc.filter_fragment_type offset");
static_assert(offsetof(MassSpatialQueryConfigDesc, filter_bool_offset) == 56, "MassSpatialQueryConfigDesc.filter_bool_offset offset");
static_assert(offsetof(MassSpatialQueryConfigDesc, filter_bool_must_be) == 60, "MassSpatialQueryConfigDesc.filter_bool_must_be offset");
static_assert(offsetof(MassSpatialQueryConfigDesc, query_type) == 61, "MassSpatialQueryConfigDesc.query_type offset");
static_assert(offsetof(MassSpatialQueryConfigDesc, collision_channel_index) == 62, "MassSpatialQueryConfigDesc.collision_channel_index offset");

// --- Food drop events ---
static_assert(sizeof(FoodDropEvent) == 32, "FoodDropEvent: i32 + i32 + [f64;3]");
static_assert(alignof(FoodDropEvent) == 8, "FoodDropEvent alignment");
static_assert(offsetof(FoodDropEvent, food_index) == 0, "FoodDropEvent.food_index offset");
static_assert(offsetof(FoodDropEvent, position) == 8, "FoodDropEvent.position offset");

// --- Decision counters ---
static_assert(sizeof(DecisionCounters) == 56, "DecisionCounters: 7 u64");
static_assert(alignof(DecisionCounters) == 8, "DecisionCounters alignment");
static_assert(sizeof(Option<GetDecisionCountersFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");
static_assert(sizeof(Option<ResetDecisionCountersFn>) == sizeof(void*),
    "Option<fn ptr> must be pointer-sized (Rust niche optimization)");

// --- Sim defaults ---
static_assert(sizeof(MassSimDefaultsDesc) == 72, "MassSimDefaultsDesc");
static_assert(alignof(MassSimDefaultsDesc) == 8, "MassSimDefaultsDesc alignment");
"#).expect("Failed to write static_asserts to Bindings.h");
}
